create table app_users (
    id        bigint generated by default as identity primary key,
    user_name varchar(255)
);

create table media_items (
    id            bigint generated by default as identity primary key,
    tmdb_id       integer                  not null,
    media_type    varchar(10)              not null,
    title         varchar(255)             not null,
    poster_path   varchar(255),
    backdrop_path varchar(255),
    overview      varchar(2000),
    release_date  date,
    vote_average  double precision,
    vote_count    integer,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    constraint uk_media_items_media_type_tmdb_id unique (media_type, tmdb_id),
    constraint ck_media_items_media_type check (media_type in ('movie', 'tv'))
);

create table watchlist_items (
    id            bigint generated by default as identity primary key,
    user_id       bigint                   not null,
    media_item_id bigint                   not null,
    added_at      timestamp(6) with time zone not null,
    constraint uk_watchlist_items_user_media unique (user_id, media_item_id),
    constraint fk_watchlist_items_user foreign key (user_id) references app_users (id),
    constraint fk_watchlist_items_media_item foreign key (media_item_id) references media_items (id)
);

create table favorite_items (
    id            bigint generated by default as identity primary key,
    user_id       bigint                   not null,
    media_item_id bigint                   not null,
    added_at      timestamp(6) with time zone not null,
    constraint uk_favorite_items_user_media unique (user_id, media_item_id),
    constraint fk_favorite_items_user foreign key (user_id) references app_users (id),
    constraint fk_favorite_items_media_item foreign key (media_item_id) references media_items (id)
);

create table ratings (
    id            bigint generated by default as identity primary key,
    user_id       bigint                   not null,
    media_item_id bigint                   not null,
    value         double precision         not null,
    rated_at      timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    constraint uk_ratings_user_media unique (user_id, media_item_id),
    constraint fk_ratings_user foreign key (user_id) references app_users (id),
    constraint fk_ratings_media_item foreign key (media_item_id) references media_items (id)
);

create table episode_ratings (
    id             bigint generated by default as identity primary key,
    user_id        bigint                   not null,
    series_item_id bigint                   not null,
    season_number  integer                  not null,
    episode_number integer                  not null,
    episode_name   varchar(255)             not null,
    still_path     varchar(255),
    air_date       date,
    value          double precision         not null,
    rated_at       timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone not null,
    constraint uk_episode_ratings_user_episode unique (user_id, series_item_id, season_number, episode_number),
    constraint fk_episode_ratings_user foreign key (user_id) references app_users (id),
    constraint fk_episode_ratings_series_item foreign key (series_item_id) references media_items (id)
);

create table user_lists (
    id                  bigint generated by default as identity primary key,
    user_id             bigint                   not null,
    name                varchar(100)             not null,
    description         varchar(1000),
    is_public           boolean                  not null,
    sort_by             varchar(30)              not null,
    cover_media_item_id bigint,
    created_at          timestamp(6) with time zone not null,
    updated_at          timestamp(6) with time zone not null,
    constraint fk_user_lists_user foreign key (user_id) references app_users (id),
    constraint fk_user_lists_cover_media_item foreign key (cover_media_item_id) references media_items (id)
);

create index idx_user_lists_user_id on user_lists (user_id);

create table user_list_items (
    id            bigint generated by default as identity primary key,
    user_list_id  bigint                   not null,
    media_item_id bigint                   not null,
    comment       varchar(1000),
    added_at      timestamp(6) with time zone not null,
    constraint uk_user_list_items_list_media unique (user_list_id, media_item_id),
    constraint fk_user_list_items_user_list foreign key (user_list_id) references user_lists (id),
    constraint fk_user_list_items_media_item foreign key (media_item_id) references media_items (id)
);
