alter table app_users drop column user_name;

alter table app_users
    add column email         varchar(255)                not null,
    add column username      varchar(30)                 not null,
    add column password_hash varchar(100)                not null,
    add column created_at    timestamp(6) with time zone not null,
    add column updated_at    timestamp(6) with time zone not null,
    add constraint uk_app_users_email unique (email);

create unique index uk_app_users_username_lower on app_users (lower(username));

create table refresh_tokens (
    id         bigint generated by default as identity primary key,
    user_id    bigint                      not null,
    token_hash varchar(64)                 not null,
    expires_at timestamp(6) with time zone not null,
    revoked_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    constraint uk_refresh_tokens_token_hash unique (token_hash),
    constraint fk_refresh_tokens_user foreign key (user_id) references app_users (id)
);

create index idx_refresh_tokens_user_id on refresh_tokens (user_id);
